version: '3.6'

services:
  # roscore:
  #   image: mins:v3
  #   network_mode: "host"
  #   restart: always
  #   command: /bin/bash -c " \
  #     source /opt/ros/noetic/setup.bash && \
  #     roscore"

  oak:
    image: "luxonis/depthai-ros:${luxonisImageTag:?error}"
    tty: true
    privileged: true
    restart: unless-stopped
    # network_mode: "host"
    networks:
      vins:
        ipv4_address: "10.20.12.2"
    # depends_on:
      # - roscore
    environment:
      DISPLAY: ${DISPLAY}
      "XAUTHORITY": ${XAUTH}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /dev:/dev/
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw

    command: /bin/bash -c "
      ros2 launch depthai_examples stereo_inertial_node.launch.py \
      enableRviz:=false stereo_fps:=30 syncNN:=false \
      enableSpatialDetection:=false depth_aligned:=false " #\
      # /stereo_inertial_publisher/imu:=/imu/data_raw"

  # ublox:
  #   image: "ublox_ros1:v1"
  #   privileged: true
  #   restart: unless-stopped
  #   network_mode: "host"
  #   # networks:
  #   #   mins:
  #   #     ipv4_address: "10.20.10.3"
  #   depends_on:
  #     # - roscore
  #     - oak
  #   # environment:
  #   #   DISPLAY: ${DISPLAY}
  #   #   "XAUTHORITY": ${XAUTH}
  #   volumes:
  #     # - /tmp/.X11-unix/:/tmp/.X11-unix/
  #     # - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
  #     # - ~/ws_docker/ws_mins/ROS2_simulator/.ros:/root/.ros
  #     - /dev/:/dev/
  #     - ~/ws_docker/ws_ublox/:/ws_ublox/
  #   command: /bin/bash -c "
  #     roslaunch ublox_gps ublox_device.launch param_file_name:=m8u_rover node_name:=gps"

  rviz:
    image: "alienkh/vins-fusion-ros2:${VinsFusionRosTag:?error}"
    tty: true
    restart: unless-stopped
    network_mode: "host"
    # networks:
    #   mins:
    #     ipv4_address: "10.20.12.4"
    depends_on:
      # - roscore
      - oak
      # - mins
    environment:
      DISPLAY: ${DISPLAY}
      "XAUTHORITY": ${XAUTH}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /home/alien/docker_ws/github/ws_vins-fusion-ros2/:/ws_vins-fusion-ros2/
    command: /bin/bash -c "
      source /opt/ros/foxy/setup.bash && \
      rviz -d /ws_vins-fusion-ros2/src/VINS-Fusion-ROS2/config/vins_rviz_config.rviz"

  rqt:
    image: "alienkh/vins-fusion-ros2:${VinsFusionRosTag:?error}"
    tty: true
    # network_mode: "host"
    networks:
      vins:
        ipv4_address: "10.20.12.5"
    restart: unless-stopped
    depends_on:
      # - roscore
      - oak
      # - mins
    environment:
      DISPLAY: ${DISPLAY}
      "XAUTHORITY": ${XAUTH}
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - /home/alien/docker_ws/github/ws_vins-fusion-ros2/:/ws_vins-fusion-ros2/
    command: /bin/bash -c "
      source /opt/ros/foxy/setup.bash && rqt"

  vins-fusion:
    image: "alienkh/vins-fusion-ros2:${VinsFusionRosTag:?error}"
    tty: true
    # network_mode: "host"
    depends_on:
      # - roscore
      - oak
      # - ublox
    networks:
      vins:
        ipv4_address: "10.20.12.6"
    restart: unless-stopped
    environment:
      DISPLAY: ${DISPLAY}
      "XAUTHORITY": ${XAUTH}

    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/ 
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /home/alien/docker_ws/github/ws_vins-fusion-ros2/:/ws_vins-fusion-ros2/
    command: /bin/bash -c "
      source /opt/ros/foxy/setup.bash && cd /ws_vins-fusion-ros2/ && \
      colcon build && source /ws_vins-fusion-ros2/install/setup.bash && \
      ros2 run vins vins_node /ws_vins-fusion-ros2/src/VINS-Fusion-ROS2/config/oak-s2/oak-s2.yaml "


networks:
  vins:
    ipam:
      # driver: bridge
      config:
        - subnet: "10.20.12.0/24"
